### ISSUE TITLE
`gaussian_blur` caused panic

### ISSUE THREAD

**Issue by shulhi** [nebgnahz/cv-rs#85]
I'm not sure if this is a bug or just my incompetency (I'm new to both Rust and OpenCV). Calling `gaussian_blur` caused the following error, 

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21
```

My code is really simple, 

```rust
extern crate cv;
use cv::highgui::*;
use cv::videoio::VideoCapture;
use cv::*;

fn main() {
    let cap = VideoCapture::new(0);
    assert!(cap.is_open());

    highgui_named_window("Window", WindowFlag::Autosize).unwrap();

    while let Some(m) = cap.read() {
        let mut m = m.cvt_color(cv::imgproc::ColorConversion::BGR2HSV);
        let size = cv::core::Size2i::new(5, 5);
        m.gaussian_blur(size, 0.9, 0.9, cv::mat::BorderType::Transparent);
        m.show("Window", 30).unwrap();
    }
}
```

At first, I had a segfault but reading OpenCV documentation reveals that the size must be an odd number. Changing the kernel size to odd number doesn't caused segfault anymore but it panicked instead.

Running gdb, I could see that it panicked after a call to `cv_gaussian_blur` here,

https://github.com/nebgnahz/cv-rs/blob/46372956e02768c968507afd2507152586c414be/src/imgproc.rs#L463

I tried to step through the function to see where exactly it failed, but it just led me to something that I don't quite understand.

**Comment by Pzixel** [comment]
Could you run with full stacktrace, please?

`RUST_BACKTRACE=1 cargo run`

**Comment by shulhi** [comment]
```
$  RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s                                                                                                                                                 
     Running `target/debug/hello`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::panicking::panic
             at libcore/panicking.rs:52
   9: __rust_maybe_catch_panic
             at /checkout/src/libcore/macros.rs:20
             at libpanic_unwind/gcc.rs:101
             at libpanic_unwind/lib.rs:108
  10: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  11: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  12: main
  13: __libc_start_main
  14: _start
fatal runtime error: failed to initiate panic, error 5
[1]    13895 abort (core dumped)  RUST_BACKTRACE=1 cargo run
```

**Comment by shulhi** [comment]
Initially I thought this might be the reason, 

https://github.com/nebgnahz/cv-rs/blob/46372956e02768c968507afd2507152586c414be/src/imgproc.rs#L462

The doc mentions that `dst` must be the same size as the `src`. I changed it to something like, 

```rust
let m = CMat::new_with_size(self.rows, self.cols, 1); // basically calls cv_mat_new_with_size
```

still the same error though.

**Comment by Pzixel** [comment]
It's clearly a rust error. `CMat::new()` has nothing to deal with exception. Unfortunately I have no camera so I cannot run it locally, so you have to investigate it yourself, I could only guide you.

The error says that some `Option<T>` that expected to be Some is None.

The only `unwrap` I see is `highgui_named_window("Window", WindowFlag::Autosize).unwrap();`. But for some reason I don't see anything in the backtrace that points to the line in user code. That's strange.

**Comment by shulhi** [comment]
I don't think it is from `highgui_named_window`. You can reproduce the same issue with the following code, there is no need for camera this time. Commenting the `gaussian_blur` line should fix it.

```rust
extern crate cv;
use cv::highgui::*;
use cv::imgcodecs::ImageReadMode;
use cv::*;

fn main() {
    let args: Vec<_> = std::env::args().collect();
    if args.len() != 2 {
        println!("Usage: display_image ImageToLoadAndDisplay");
        std::process::exit(-1);
    }

    let mat = Mat::from_path(&args[1], ImageReadMode::Color).expect("Failed to read from path");
    let size = cv::core::Size2i::new(5, 5);

    if !mat.is_valid() {
        println!("Could not open or find the image");
        std::process::exit(-1);
    }

    mat.gaussian_blur(size, 0.9, 0.9, cv::mat::BorderType::Transparent);
    highgui_named_window("Display window", WindowFlag::Normal);
    mat.show("Display window", 0);
}
```

I stepped through all the codes, still no idea what's going though but it looks like it panicked after this line, 

```
cv::_InputArray::init (this=0x7fffffffd260, _flags=16842752, _obj=0x7fffe7e42500) at /usr/local/include/opencv2/core/mat.inl.hpp:67
67	{ flags = _flags; obj = (void*)_obj; }
(gdb) 
[New Thread 0x7fffe7dff700 (LWP 7036)]
[New Thread 0x7fffe75fe700 (LWP 7037)]
[New Thread 0x7fffe69ff700 (LWP 7038)]
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
fatal runtime error: failed to initiate panic, error 5
```

**Comment by Pzixel** [comment]
Hmm, works for me

![image](https://user-images.githubusercontent.com/11201122/42504182-920dd2c2-8443-11e8-91d0-88572e7de85b.png)

I only changed the border type to default because I was getting `Unknown/unsupported border type` for transparent.
